# The Numpy library

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
A = [i for i in range(10)]
print(A)

In [ ]:
A[-2:]

In [ ]:
B = np.arange(1,10)
C = np.arange(11,20)
print(B)
print(C)

In [ ]:
print(B**2)

In [ ]:
x = np.arange(-.1,.1,.0001)
y = x*np.sin(1/x)
plt.plot(x,y);

In [ ]:
A = np.full((5,2), 0)
print(A)

In [ ]:
AA = np.ones((5,2))
print(AA)

In [ ]:
C = np.eye(3)
print(C)

In [ ]:
CC = 2*np.random.rand(3,3) - np.full((3,3), 1)
print(CC)

In [ ]:
CC_new = CC.reshape(9,1)
print(CC_new)

In [ ]:
print(CC.flatten())

In [ ]:
A = np.random.rand(4,4)
B = np.full((4,4), 1)
print(A)
print(B)

In [ ]:
# Dot product is not commutative
print(np.dot(A,B))
print(np.dot(B,A))

In [ ]:
A.min()

In [ ]:
A[1:3,1:3]

## EXERCISES

1. Make a (10, 10) array with 1 on all its four borders and 0's inside
Like this (4,4) array:  
[[1,1,1,1]  
 [1,0,0,1]  
 [1,0,0,1]  
 [1,1,1,1]]

In [5]:
A = np.zeros((10,10))
A[0, :] = 1  # first row
A[-1, :] = 1  # last row
A[:, 0] = 1  # first column
A[:, -1] = 1  # last column
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Substract the mean of each row of a 2D array.
Check the numpy doc https://numpy.org/doc/stable/index.html  
in particular the function np.sum()

In [12]:
B = np.random.rand(4,4)
print(B)

[[0.79944337 0.36119596 0.63531332 0.18664146]
 [0.81948198 0.39824793 0.82960994 0.91667427]
 [0.38339185 0.35616812 0.14995207 0.24373905]
 [0.10293893 0.60942428 0.4628129  0.24823469]]


In [28]:
A1=np.mean(B[0, :])


In [29]:
A2=np.mean(B[1, :])

In [30]:
A3=np.mean(B[2, ])

In [31]:
A4=np.mean(B[3, ])

In [33]:
SubB = B - np.array([A1, A2, A3, A4])
print(SubB)

[[ 0.30379484 -0.37980757  0.35200055 -0.16921124]
 [ 0.32383345 -0.3427556   0.54629717  0.56082157]
 [-0.11225668 -0.38483541 -0.1333607  -0.11211365]
 [-0.3927096  -0.13157925  0.17950013 -0.10761801]]


3. Find the nearest value from a value in an array
Check the numpy doc for the functions np.abs() and np.min() 

In [47]:
def find_nearest(C, val): 
    idx = (np.abs(C - val)).argmin()
    return C[idx]

C = np.random.random(10)
print(C)
val = 0.5 
print(find_nearest(C, val))

[0.61394421 0.61615544 0.25432495 0.88830476 0.44043868 0.26306677
 0.93646418 0.99485013 0.72330082 0.87493898]
0.44043868405783904


4. Given two (5,5) numpy arrays A and B find the sum of diagonal elements of
the (5,5) numpy array np.dot(A,B) and the sum of the diagonal elements of
the (5,5) numpy array np.dot(B,A). (Hint check np.diag()) Try this for a few arrays A and B
possibly by definition a function.

In [61]:
A = np.random.rand(5,5)


B = np.random.rand(5,5) 


In [73]:
C = (np.dot(A,B)) 

D = (np.dot(B,A))

print(C)
print(D)

[[1.42223972 1.22993002 1.38848946 1.80186751 1.49390014]
 [1.66870134 1.37588728 1.76031207 1.81490458 1.22235019]
 [1.77175161 1.68237266 1.45499794 1.90105168 1.48496329]
 [1.81557523 1.77280828 1.09908949 1.56995594 1.34447187]
 [1.80140807 1.47360021 1.47242261 1.39839013 0.92759909]]
[[2.07753829 1.46417242 2.2727393  2.56178931 2.27687428]
 [1.24902484 0.88919924 1.42825768 1.44695237 1.56517533]
 [1.55616206 1.01869131 0.54430593 1.48349919 0.95291625]
 [1.41567039 0.90261933 1.26605867 1.53129774 1.63864101]
 [1.50315431 1.08154831 1.96715385 2.035738   1.70833878]]


In [72]:
Diag_C = np.diagonal(C) 
Diag_D = np.diagonal(D)

print(Diag_C)
print(Diag_D)


[1.42223972 1.37588728 1.45499794 1.56995594 0.92759909]
[2.07753829 0.88919924 0.54430593 1.53129774 1.70833878]


In [75]:
np.sum(Diag_C)


6.750679974132113

In [76]:
np.sum(Diag_D)

6.750679974132113

In [80]:
# function of diagonal element sum 
def sum_d(A, B):
    # Compute the dot product of A and B
    C = np.dot(A, B)
    # Extract diagonal elements
    diagonal_elements = np.diagonal(C)
    # Compute the sum of diagonal elements
    diagonal_sum = np.sum(diagonal_elements)
    return diagonal_sum

In [81]:
A = np.random.rand(6,6)
B = np.random.rand(6,6)

sumD = sum_d(A,B)
print(sumD)

8.41820960837866
